- src/commands/potato.ts
- src/discord.ts
> feat: potatoコマンドの設定を追加

- src/commands/bassline.ts
- src/discord.ts
> feat: basslineコマンドを追加

- src/commands/powa.ts
- src/discord.ts
> feat: powaコマンドの実装

- src/commands/super.ts
- src/discord.ts
> feat: superコマンドの実装

- src/discord.ts
> feat: permissionを確認する処理を追加

- .github/workflows/jaotan-review.yml
以下の条件にすべて合致する場合に、jaotanがApproveする
- プルリクエストでコメントされたとき
- プルリクエスト作者が ＠book000 である
- `@jaotan` が含まれている
- `@review` が含まれている
> ci: jaotanによるレビューフローの追加

- .devcontainer/devcontainer.json
> feat: devcontainer

- src/discord.ts
- src/events/meeting-vote-reaction.ts
- src/events/pin-prefix.ts
- src/events/pin-reaction.ts
> feat: ピン留めまわりの機能実装

- src/config.ts
- src/discord.ts
- src/events/vc-speech-log-url.ts
- src/tasks/meeting-vote.ts
> feat: vc-speech-logへのメッセージリンクを貼った場合の処理を実装

- src/discord.ts
- src/features/meeting-vote.ts
> fix: 投票メンバーからBotを除外 & Partialsを増やしてみる

- .github/renovate.json
> chore: renovateをbook000/templatesに依存させなくする

- src/events/meeting-vote-reaction.ts
- src/features/meeting-vote.ts
> feat: 過半数計算の修正、空白投稿の扱い修正など対応

- src/events/pin-prefix.ts
- src/events/pin-reaction.ts
> feat: ピン留めの際、チャンネルタイプチェックにスレッドを対象とするように

- src/discord.ts
- src/events/tweet-embed.ts
- close #198 
綺麗に表示するにはスクレイピングしないとならないので、またこんど。
> feat: ツイートへのリンクが貼られた際、embedで内容をリプライする

- src/commands/controrandja.ts
- src/commands/toar.ts
- src/commands/toarja.ts
- src/commands/tochaos.ts
- src/commands/tohe.ts
- src/commands/toheja.ts
- src/commands/toja.ts
- src/commands/tojaen.ts
- src/commands/tokoja.ts
- src/commands/torandja.ts
- src/commands/toswja.ts
- src/commands/tozh.ts
- src/commands/tozhja.ts
- src/commands/translate.ts
- src/discord.ts
- src/features/translate.ts
- close #160 
---
以下のコマンドを追加
- contorandja
- toar
- toarja
- tochaos
- tohe
- toheja
- toja
- tojaen
- tokoja
- torandja
- toswja
- tozh
- tozhja
次のコマンドの挙動を一部変更
- translate
> feat: 翻訳系のコマンドを追加

- src/config.ts
- src/discord.ts
- src/events/new-discussion-mention.ts
> feat: discussionフォーラムでスレッドが立ったらAdminにサイレントメンションする

- .vscode/settings.json
- Dockerfile
- package.json
- pnpm-lock.yaml
- src/discord.ts
- src/features/birthday.ts
- src/jobs/everyday.ts
- src/jobs/index.ts
> feat: 毎日0時に#generalへメッセージを送信する機能の追加

- src/jobs/everyday.ts
> fix: 記念日詳細が複数列挙される不具合修正

- src/commands/birthday.ts
- src/discord.ts
- src/features/birthday.ts
This pull request adds a new command called "birthday" to the Discord bot. The command allows users to set their birthday, view their current birthday settings, force a specific age, and delete their birthday.
- close #281
> feat: add birthday command

- docs/commands/index.md
- docs/commands/toen.md
- src/commands/toen.ts
- src/discord.ts
> feat: toenコマンドの実装

- src/jobs/everyday.ts
> feat: 誕生日のユーザーがいるとき、birthdayコマンドの利用方法について説明するように

- src/events/nitrotan-message.ts
- src/events/nitrotan-reaction.ts
- src/features/nitrotan.ts
- src/tasks/nitrotan-profile.ts
> fix: nitrotanのチェック処理を改善

- src/features/nitrotan.ts
> feat(nitrotan): メッセージのembed化

- docs/features/index.md
- docs/features/reply.md
- src/config.ts
- src/discord.ts
- src/events/reply.ts
- src/features/mebo.ts
> feat: jaotanとのチャット機能を実装
